---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init-mongo.sh: |
    #!/bin/sh

    if which mongosh > /dev/null 2>&1; then
      mongo_init_bin='mongosh'
    else
      mongo_init_bin='mongo'
    fi
    "${mongo_init_bin}" <<EOF
    use admin
    db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
    use unifi
    db.createUser({
      user: "${MONGO_ADD_USER_NAME}",
      pwd: "${MONGO_ADD_USER_PASSWORD}",
      roles: [
        { db: "unifi", role: "readWrite" },
        { db: "unifi_stat", role: "readWrite" },
        { db: "unifi", role: "dbOwner" },
        { db: "unifi_stat", role: "dbOwner" }
      ]
    })
    EOF
