---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/unifi/config"
  claimRef:
    name: unifi
    namespace: unifi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi